### ISSUE TITLE
teacher_path

### ISSUE THREAD

**Issue by mjmaher987** [goldblum/AdversariallyRobustDistillation#9]
what should i locate in teacher_path exactly?! i dont have any distilled model

**Comment by goldblum** [comment]
You need to use a robustly trained teacher model.  We used a TRADES model as a teacher, and we got it straight from their repo (https://github.com/yaodongyu/TRADES).  We recently stopped hosting this since it was a copy of the existing model from their repo, and it was hosted on my personal Drive account.

**Comment by mjmaher987** [comment]
What model should i download and load if i want to reproduce the table 1 of the article?

**Comment by goldblum** [comment]
The CIFAR-10 teacher here is the TRADES model we use for our best ARD results:
https://github.com/yaodongyu/TRADES

We no longer have access to the exact teacher checkpoints used for Table 1.

**Comment by mjmaher987** [comment]
thanks
